# Development Profile Configuration
spring:
  config:
    activate:
      on-profile: development
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Logging for Development
logging:
  level:
    root: DEBUG
    com.fiap: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    io.awspring.cloud.sqs: DEBUG
    software.amazon.awssdk: DEBUG
    software.amazon.awssdk.request: DEBUG

# Datadog (disabled in dev)
dd:
  trace:
    enabled: false

# AWS SQS Configuration
aws:
  region: ${AWS_REGION:us-east-2}
