# Development Profile Configuration
spring:
  config:
    activate:
      on-profile: development
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Logging for Development
logging:
  level:
    root: INFO
    com.fiap: INFO
    org.springframework.web: INFO
    org.springframework.security: WARN
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    io.awspring.cloud.sqs: INFO
    software.amazon.awssdk: INFO
    software.amazon.awssdk.request: INFO

# Datadog (enabled in development)
dd:
  trace:
    enabled: true

# AWS SQS Configuration
aws:
  region: ${AWS_REGION:us-east-2}
