services:
  postgres:
    image: postgres:15-alpine
    container_name: stock-service-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: challengeone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d challengeone"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
