name: CI/CD - Spring Boot Build & Docker Hub Deploy

on:
  push:
    branches:
      - main
      - homologation
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  ENVIRONMENT: ${{ github.ref_name == 'main' && 'production' || (github.ref_name == 'homologation' && 'homologation' || 'dev') }}
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/stock-service

jobs:
  build-and-test:
    name: Build and Test Project
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || (github.ref_name == 'homologation' && 'homologation' || 'dev') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build and Test with Maven
        run: mvn -B clean package


  push-and-deploy:
    name: Push Image & Deploy Infra
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || (github.ref_name == 'homologation' && 'homologation' || 'dev') }}
    needs: build-and-test

    env:
      TERRAFORM_DIR: infra/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment tag
        id: envtag
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          echo "TAG=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ env.TAG }} .
          docker push $IMAGE_NAME:${{ env.TAG }}
          docker tag $IMAGE_NAME:${{ env.TAG }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform init -backend-config="key=v4/service-stock/${{ env.ENVIRONMENT }}/terraform.tfstate"

      - name: Terraform Apply
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform apply -auto-approve
        env:
          TF_VAR_environment: ${{ env.ENVIRONMENT }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_image_tag: ${{ env.TAG }}